version: '3'


services: 
  # Django
  web:
    build: .
    volumes:
      - .:/src

  web_migrate:
    extends:
      service: web
    command: python manage.py migrate

  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  # telegram bot
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - .:/src
    restart: always


  # Celery
  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A paxfull_gifts worker -l info
    volumes:
      - .:/src
    env_file:
      - ./.env
    depends_on:
      - redis 
      - web_run
    
  celery-beat:
    build: .
    command: celery -A paxfull_gifts worker -l info
    volumes:
      - .:/src
    env_file:
      - ./.env
    depends_on:
      - redis
      - web_run