version: '3'


services: 
  # Django
  web:
    build: .
    volumes:
      - .:/src

  web_migrate:
    extends:
      service: web
    command: python manage.py migrate

  web_run:
    extends:
      service: web
    command: gunicorn paxfull_gifts.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  # telegram bot
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    env_file:
      - ./.env.local
    volumes:
      - .:/src
    restart: always

  # Binance stream
  binance:
    build: .
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    env_file:
      - ./.env.local
    volumes:
      - .:/src
    restart: always
    command: python _binance_webhook.py

  # Celery worker/beat
  redis:
    image: redis:alpine
    ports:
    - "6379:6379" 

  celery:
    build: .
    command: celery -A paxfull_gifts worker -l info
    volumes:
      - .:/src
    env_file:
      - ./.env.local
    depends_on:
      - redis 
      - web_run
    
  celery-beat:
    build: .
    command: celery -A paxfull_gifts beat -l info
    volumes:
      - .:/src
    env_file:
      - ./.env.local
    depends_on:
      - redis
      - web_run